# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
#  - name: Recent News
#    url: '#recent-news'
#    weight: 20
  - name: Posts
    url: https://www.zhihu.com/people/lyx-55-20/posts
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Projects
    url: '#project'
    weight: 40
  - name: Honor & Award & Service
    url: '#reward'
    weight: 50
  - name: CV
    url: materials/cv.pdf
    weight: 60


# - name: CV
#   url: '#featured'
#   weight: 50
# - name: Contact
#   url: '#contact'
#   weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
